<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>

<hr>

<a href="https://lms.clarusway.com/mod/lesson/view.php?id=2463&pageid=4531&startlastseen=no"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/2-DAwPY/DAwPy_S01_(Numpy_Arrays).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="90" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DAwPy_S1_%28Numpy_Arrays%29/DAwPy_S1_%28Numpy_Arrays%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="100" height="100" title="Open and Execute in nbviewer"></a><br/>

<hr>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="500" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="text-align: center;"><img src="https://i.ibb.co/XS0bxSH/best-bootcamps.png" width="300" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid"
alt="CLRSWY_Courses"></p>

# <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Tasks for Session-1</p>

## Task 1 : Task: Random Matrix Generation and Operations:

### 1a. Generate a 4x4 matrix filled with random values.

In [3]:
import numpy as np


In [9]:
arr = np.random.rand(4, 4)
print(arr)

[[0.65631784 0.34197529 0.5018068  0.36107284]
 [0.99635822 0.15305152 0.33156472 0.81503804]
 [0.10408791 0.19906543 0.28625648 0.87258749]
 [0.14591421 0.83300003 0.84158253 0.85856718]]


### 1b. Calculate the row sums of the matrix.

In [10]:
np.sum(arr, axis=1)

array([1.86117278, 2.29601251, 1.46199731, 2.67906395])

### 1c. Calculate the column means of the matrix.

In [15]:
np.mean(arr, axis=0)

array([0.47566954, 0.38177307, 0.49030263, 0.72681639])

In [13]:
from scipy import stats
np.mean(arr, axis=0)


array([0.47566954, 0.38177307, 0.49030263, 0.72681639])

### 1d. Find the sum of the diagonal elements of the matrix.

In [16]:
np.trace(arr)

1.9541930192420351

## Task 2: Array Sorting and Indexing:

### 2a. Create an array of random numbers from 1 to 20.

In [23]:
num_rand = np.random.randint(1, 20, 20)
print(num_rand)

[17  9 16 19  2 17  5 16 12 17 12 10 13 15 12 16  7 11 17  5]


### 2b. Sort the array in descending order.

In [24]:
np.sort(num_rand)[::-1]

array([19, 17, 17, 17, 17, 16, 16, 16, 15, 13, 12, 12, 12, 11, 10,  9,  7,
        5,  5,  2])

### 2c. Find the minimum and maximum elements of the array.

In [25]:
np.max(num_rand)

19

### 2d. Select the first half of the array (the first 10 elements) and reverse them.

In [29]:
num_rand[:10][::-1]

array([17, 12, 16,  5, 17,  2, 19, 16,  9, 17])

## Task 3: Convert the Arrays:

### 3a. Create an array with elements [-1, 0, 1, 2, 3].

In [31]:
arr1 = np.array([-1, 0, 1, 2, 3])

### 3b. Convert the array into a matrix and square each element.

In [33]:
arr1_matrix = arr1.reshape(-1, 1)
square_matrix = arr1_matrix ** 2
print(square_matrix)

[[1]
 [0]
 [1]
 [4]
 [9]]


### 3c. Convert the matrix back to a one-dimensional array.

In [36]:
one_dimensional_array = np.ravel(square_matrix)
print(one_dimensional_array)

[1 0 1 4 9]


### 3d. Convert each element of the array to its absolute value

In [40]:
abs_arr = np.abs(arr1)
print(abs_arr)  #-1 i elde etmek icin napilir?

[1 0 1 2 3]


<hr>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:150%; text-align:center; border-radius:10px 10px;">The End of Task</p>


<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid"
alt="CLRSWY"></p>


<br><br><br>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="450" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>